version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: lango-kiara-{{ checksum "pom.xml" }}
      - run: mvn clean install -pl core,rank,scoreboard
      - store_artifacts:
          path: target/
      - save_cache:
          paths:
            - ~/.m2
          key: lango-kiara-{{ checksum "pom.xml" }}